konnectors/cozy-konnector-template

README.md
data/env.js
data/env_development.js
data/env_standalone.js
package.json

This is a proposition of "simplification" of the npm script commands used in each connector.
With this, the konnector developer does not need to run the yarn init:dev:account anymore. It is run automatically when using the yarn dev command. If the ./data/env_fields.json does not exist, an error message is displayed.
This also needs an update of the cozy-konnector-libs package which is not published yet. Then a yarn link is needed with the master version of cozy-konnector-libs, at the moment.
The downside is that we need to update all the konnectors one more time to use this. But this goes in the sense of facilitating the life of konnectors developpeurs (I think)

feat: konnector script commands simplification

---

package.json

@nicofrand has spotted this error: in the README, we say to run `yarn deploy` to have the konnector ready to be sued with an URL using the `build` branch, but git-directory-deploy pushes to `gh-pages` per default.

fix: Push to the build branch with yarn deploy

---

README.md

Thanks to @nicofrand for debugging this!

fix: Explain to give the repo scope to the github token for deploys

---

CONTRIBUTING.md

Restore [checkbox] link that points to github markdown explanation on task lists

Restore missing link in CONTRIBUTING.md

---

package.json

lint script used it without the package being dependent to it

Add standardjs to dependencies

---

README.md

A dot had been substituted with an hyphen
s/-json/.json/

Fix typo in konnector-dev-config.json file name

---

.travis.yml

And not for each PR during the "merge" build.
It avoids unwanted commit in the build branch.

Deploy to build only on master

---

package.json

While trying to follow [the documentation](https://docs.cozy.io/fr/dev/konnector/#cozy-konnector-template-and-standalone-mode) I got an error when I executed the standalone script : 
```
Error: Cannot find module '/home/drazik/workspace/cozy/cozy-konnector-template/index.js'
```
I fixed it by providing the `src/index.js` path to the script.

fix: add file path to standalone script

---

package.json
yarn.lock

Since we now use eslint-config-cozy-app@0.5.x and prettier is built in, we don't need the direct dependency to prettier and the format script anymore.

feat: remove direct dependency to prettier and format script

---

.travis.yml
manifest.konnector

I hope this is the last change concerning registry deployment : 
- no `-collect` prefix
- there is no need for `prod` and `latest` branches now
- manifest attributes use snake case
- a commit on master deploys a dev version on the registry
- a commit with a tag deploys a stable version on the registry

fix: manifest typos + now deploy stable version on tags

---

README.md

Ce nouveau template de readme est beaucoup mieux que le précédant qui était trop long. 
J'ai surtout ajouté le lien vers la documentation des connecteurs et les info de base pour lancer le connecteur en mode standalone (ajout du fichier avec les credentials et commande de lancement).
=> il faut vérifier la syntaxe des credentials dans le champs fields dont je ne suis pas certain

link to konnectors development guide

---

manifest.konnector
src/index.js

- async/await is used to make async code more readable than promises
- the signin function is used which handles a lot of csrf token cases
- the scrape function is also used and it avoids some cheerio magic and is nicer to read
- shows some login code for quotes.toscrape.com, even if books.toscrape.com is scraped after
- saveBills is used, which is the most common case in connectors at the moment

feat: new template which is supposed to be more representative of a real connector

---

manifest.konnector

As discussed [here](https://mattermost.cozycloud.cc/test-team/pl/x1983pu4tpf6p8qa6dbezzh3hc), it seems relevant to start using a `manifest_version`, to prevent breaking changes in manifest attributes in the future.

Add 'manifest_version' to manifest

---

webpack.config.js

- We added a `branches: except: build` to the `.travis.yml`
- But the `.travis.yml` is not copied on build branch
- So it was useless
- Copy the `.travis.yml` file into the build branch

Prevent building build branch

---

CODEOWNERS

fix #92
this allows members to be manage once for all inside github

chore: use a team to manage codeowners

---

webpack.config.js

Optimise the icon svg via svgo on the webpack build.
The linter is not happy about the console statement but I can't have an empty catch statement so I kept the comment here.

Optimize konnectors icon (SVG) on build

---

bin/generate_travis_deploy_key

When encrypting github deploy key, the following error may occurs if the new konnector repository is not yet available in Travis:
```
$> travis encrypt-file github_deploy_key --add --no-interactive -w /tmp/github_deploy_key -f
detected repository as konnectors/debug
encrypting github_deploy_key for konnectors/debug
storing result as github_deploy_key.enc
storing secure env variables for decryption
resource not found ({"error":"Couldn't find repository"})
```
In this PR we fix this problem by running `travis sync` in `bin/generate_travis_deploy_key`.

Run travis sync before encrypting deploy key

---

webpack.config.js

Here is a change to the template which will hide the warning messages for which we cannot do anything like : 
WARNING in ../libs/node_modules/bindings/bindings.js 76:22-40
Critical dependency: the request of a dependency is an expression

fix: critical dependencies

---

package.json

Since run-dev has been introduced, we need to use konnector-dev to read `konnector-dev-config.json`.

fix: Use konnector-dev and konnector-standalone

---

package.json

Move hooks config from "scripts" field to "husky" field.
Setting pre-commit script in package.json is going to be be deprecated.
https://github.com/typicode/husky#upgrading-from-014
https://github.com/typicode/husky/blob/master/CHANGELOG.md#100

Update Husky config

---

webpack.config.js

Some webpack setup to allow [cozy-konnector-libs to get the manifest](https://github.com/konnectors/libs/pull/422)

feat: add access to the connector manifest via webpack

---

babel.config.json

This is needed since the version 1.3.0 of cozy-konnector-build

fix: add babel configuration file

---

README.md

Fixes for README.md template:
- Remove `<` signs where we don't want to interpret it as an HTML tag
- Fix twitter url
- Add mastodon URL

docs: Fix README.md template

---

webpack.config.js

Remove unused README, LICENCE and .travis.yml files from built archive
These files are unneeded and removing them make the package smaller to download and execute on servers

chore: Remove unneeded files from built asset
